services:
  hrms_next_frontend_prod:
    container_name: hrms_frontend_prod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_APP_BASE_URL: ${NEXT_APP_BASE_URL}
    restart: always
    ports:
      - "3080:3000"
    environment:
      - NEXT_APP_BASE_URL=${NEXT_APP_BASE_URL}

